import type { NextPage } from "next";
import Head from "next/head";
import Banner from "../components/Banner";
import Header from "../components/Header";
import requests from "../utils/requests";

const Home: NextPage = ({ trendingNow }) => {
	return (
		<>
			<Head>
				<title>Home - Netflix</title>
				<meta name="description" content="Generated by create next app" />
				<link rel="icon" href="/favicon.ico" />
			</Head>

			<Header />

			<main>
				<Banner trendingNow={trendingNow} />
				<section>
					{/* Row */}
					{/* Row */}
					{/* Row */}
					{/* Row */}
					{/* Row */}
					{/* Row */}
					{/* Row */}
					{/* Row */}
					{/* Row */}
				</section>
			</main>
		</>
	);
};

export default Home;

export const getServerSideProps = async () => {
	const trendingNow = await fetch(requests.fetchTrending).then((res) =>
		res.json()
	);

	return {
		props: {
			trendingNow: trendingNow.results,
		},
	};
};
